plugins { id 'java-library' }

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

sourceSets.main.java.srcDirs = ['src']

dependencies {
    api 'com.badlogicgames.gdx:gdx:1.12.1'
    api 'com.badlogicgames.gdx:gdx-box2d:1.12.1'
    api 'org.luaj:luaj-jse:3.0.1'
}

sourceSets.main.resources.srcDirs = ['assets']
// do not double-copy assets into jar resources root
processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
